name: fan-in-fan-out

on: qwe

jobs:
  build:
   runs-on: ubuntu-latest
   strategy:
     matrix:
      os: [windows,mac,os]
   steps:
     - run: echo "..."
     - uses: actions/upload-artifact@v1
       with:
         name: build.zip

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
     - run: echo "..."

  checks:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
     - run: echo "..."

  test-A-1:
   runs-on: ubuntu-latest
   needs: [lint,checks]
   strategy:
     matrix:
      nodeVer: [4,6,8]
      os: [lin, win, mac]
   steps:
     - run: echo "..."

  test-A-2:
   runs-on: ubuntu-latest
   needs: [test-A-1]
   steps:
     - run: echo "..."

  test-B:
   runs-on: ubuntu-latest
   needs: [lint,checks]
   strategy:
     matrix:
      nodeVer: [4,6,8]
   steps:
     - run: echo "..."

  test-C:
   runs-on: ubuntu-latest
   needs: [lint,checks]
   strategy:
     matrix:
      nodeVer: [4,6,8]
   steps:
     - run: echo "..."

  staging:
   runs-on: ubuntu-latest
   needs: [test-A-2,test-B,test-C]
   steps:
     - run: echo "..."

  uat-test-A:
   runs-on: ubuntu-latest
   needs: [staging]
   steps:
     - run: echo "..."

  uat-test-B:
   runs-on: ubuntu-latest
   needs: [staging]
   steps:
     - run: echo "..."

  uat-test-C:
   runs-on: ubuntu-latest
   needs: [staging]
   steps:
     - run: echo "..."

  deploy:
   runs-on: ubuntu-latest
   needs: [uat-test-A,uat-test-B,uat-test-C]
   steps:
     - run: echo "..."
