name: CI

on:
  push:
    branches: [ qwe ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: echo Build Complete
  test-1:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Test Complete
  test-2:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Test Complete
  deploy:
    needs: [test-1,test-2]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo Deploy Complete
