name: CI

on:
  push:
    branches: [ qwe ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        v: [1,3,5]
        os: [lin, win,mac]
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: echo Build Complete
  test-1:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Test Complete
  test-2:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Test Complete
  test-3:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Test Complete
  stage:
    needs: [test-1,test-2,test-3]
    strategy:
      matrix:
        env: [mac, linux]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo Stage Deploy Complete
  security-test:
    needs: [test-1]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Test Complete
  deploy:
    needs: [stage,security-test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo Deploy Complete
