name: CI

on: [push]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        v: [1,3]
        os: [lin, win, mac]
    steps:
      - name: build
        run: echo Build Complete
  
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [lin, win, mac]
    steps:
      - name: build
        run: echo Build Complete
  
  test-A:
    needs: [build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Test Complete
        
  test-B:
    needs: [build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Test Complete
        
  test-1:
    needs: [build-backend]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Test Complete
        
  test-2:
    needs: [build-backend]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Test Complete
        
  test-3:
    needs: [build-backend]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Test Complete
  
  integration-test:
    needs: [test-1,test-2,test-3,test-A,test-B]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Test Complete
  
  security-test:
    needs: [integration-test]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Test Complete
        
  stage:
    needs: [integration-test]
    strategy:
      matrix:
        env: [mac, linux]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo Stage Deploy Complete
            
  deploy:
    needs: [stage,security-test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo Deploy Complete
