name: Python

on: [push]

jobs:
  build:
    name: visualizer
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      
      - name: Setup Python
        uses: actions/setup-python@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt
      
      - name: Run visualizer
        run: |
          python .github/workflows/visualizer.py 
 
