name: Python

on: [push]

jobs:
  build:
    name: visualizer
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      
      - name: Setup Python
        uses: actions/setup-python@v2
      
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          pip install -r .github/visualizer/requirements.txt
          
      - name: Install graphviz
        run: |
          sudo apt-get install graphviz
      
      - name: Run visualizer
        run: |
          python .github/visualizer/visualizer.py .github/workflows/main.yml True True
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          path: Digraph.gv.pdf          
      
 
